Repository diegosneves/conectar-doacoes, pull requests merged in 2024-08, with the labels that each got.

#79 feat/i68 :art: [CORE/REST] - Criação da Interface DonationServiceContract e Adaptação do DonationEntityServiceImpl
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DonationEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/core/service/DonationService.java
  src/main/java/diegosneves/github/conectardoacoes/core/service/DonationServiceContract.java
  src/test/java/diegosneves/github/conectardoacoes/core/service/DonationServiceTest.java
Labels: Technical Debt

#80 feat/i71 [REST] - Refatoração do Enum ExceptionDetails para Adequação dos HttpStatus
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/enums/ExceptionDetails.java
Labels: Technical Debt

#81 feat/i72 - [REST] - Refatoração da Classe CustomException
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/AddressEntityFailuresException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/ConstructorDefaultUndefinedException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/CustomException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/DonationEntityFailuresException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/MapperFailureException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/ShelterEntityFailuresException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/UserEntityFailuresException.java
Labels: Technical Debt

#82 feat/i69 :art: [CORE/REST] - Criação da Interface AddressServiceContract e Adaptação do AddressEntityServiceImpl
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/core/service/AddressService.java
  src/main/java/diegosneves/github/conectardoacoes/core/service/AddressServiceContract.java
  src/test/java/diegosneves/github/conectardoacoes/core/service/AddressServiceTest.java
Labels: Technical Debt

#83 feat/i18 :art: [REST] - Implantação de Consulta à API externa de CEP
  pom.xml
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/adapter/HttpAdapter.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/adapter/RestTemplateSimpleWebClient.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/adapter/RetrieveAddressAdapter.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/config/web/OpenApiConfig.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/AddressController.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/AddressControllerImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/dto/AddressApiResponseDTO.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/enums/ExceptionDetails.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/ExternalApiFailureException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/response/AddressApiResponse.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/AddressEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImpl.java
  src/main/resources/application.yaml
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImplTest.java
Labels: feature, poc

#84 feat/i31 [REST] - Criação de Novo Endpoint para Listagem de Abrigos com Paginação.
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/ShelterController.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/ShelterControllerImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/repository/ShelterRepository.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/ShelterEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/repository/ShelterRepositoryIntegrationTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImplTest.java
Labels: feature

#92 feat/i88 :sparkles: Criar Entidade de Lista de Itens para Doação
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/model/DepositEntity.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/model/DonorDeposit.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/repository/DepositRepository.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/repository/DonorDepositRepository.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/repository/DonorDepositRepositoryTest.java
Labels: feature, task

#94 feat/i89 :sparkles: Criar uma Service para a Nova Entidade
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/dto/DepositDTO.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/enums/ExceptionDetails.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/DepositEntityFailuresException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/DepositProcessingException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/factory/DepositFactory.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/factory/DonorDepositFactory.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/RegisteredDepositResponseFromDonorDepositMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/request/DepositDonationRequest.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/response/RegisteredDepositResponse.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/DepositEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/DonorDepositService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DepositEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DonorDepositServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/RegisteredDepositResponseFromDonorDepositMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DepositEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DonorDepositServiceImplTest.java
Labels: feature, task

#95 feat/i90 :sparkles: Criar Endpoint para Adicionar Itens à Lista do Usuário Doador
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/config/web/OpenApiConfig.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/DonorDepositController.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/DonorDepositControllerImpl.java
Labels: feature, task

#96 feat/i91 - Integrar a Nova Funcionalidade com o Usuário Doador
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImplTest.java
Labels: feature, task
