Repository diegosneves/conectar-doacoes, pull requests merged in 2024-07, with the labels that each got.

#23 Feat/i4 :sparkles: [REST] - Implementação do Cadastro de Usuários (Responsável e Doador)
  Release_Notes.md
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/UserController.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/UserControllerImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/repository/ShelterRepository.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/repository/UserRepository.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/request/UserEntityCreationRequest.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/response/UserEntityCreatedResponse.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/UserEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/repository/UserRepositoryTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImplTest.java
Labels: feature

#38 spy/sonar :test_tube: Adiciona token SONAR e configura análise SonarCloud no workflow CI
  .github/workflows/ci-develop.yaml
  .github/workflows/sonar-cloud.yaml
  Release_Notes.md
  pom.xml
Labels: question

#40 feat/i39 :recycle: [REST] - Verificação e Correção de Itens Informados pelo SonarCloud
  Release_Notes.md
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/BuilderMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/core/utils/ValidationUtils.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/ShelterControllerImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/core/domain/user/entity/UserTest.java
Labels: Technical Debt

#41 feat/i24 :bug: [REST] - Adição de Validação no Método createShelter
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImplTest.java
Labels: Technical Debt

#43 feat/i34 :sparkles: [REST] - Criação de Classe de Serviço para a Entity Address
  README.md
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/AddressEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImplTest.java
Labels: feature

#45 feat/i26 :loud_sound: [REST] - Implementação de Logs para Monitoramento de Exceções
  README.md
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/config/handler/ControllerExceptionHandler.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/AddressMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/DonationMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/core/utils/ValidationUtils.java
Labels: feature

#47 feat/i46 :construction_worker: [CI/CD] - Melhoria nos pipelines de CI/CD para gerenciamento de imagens Docker
  .github/workflows/ci-hlg.yaml
  .github/workflows/ci-prod.yaml
Labels: feature

#48 [PRE-RELEASE] - Preparação para a Versão 1.1.0
  .github/workflows/ci-hlg.yaml
  .github/workflows/ci-prod.yaml
  README.md
  Release_Notes.md
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/config/handler/ControllerExceptionHandler.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/AddressMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/BuilderMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/DonationMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/repository/ShelterRepository.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/AddressEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/core/utils/ValidationUtils.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/ShelterControllerImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/repository/ShelterRepositoryIntegrationTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/core/domain/user/entity/UserTest.java
Labels: release

#49 feat/i46 :construction_worker: Atualiza condições para construção e e…
  .github/workflows/ci-hlg.yaml
  .github/workflows/ci-prod.yaml
Labels: feature

#50 Develop
  .github/workflows/ci-hlg.yaml
  .github/workflows/ci-prod.yaml
Labels: bug

#51 feat/i46 :green_heart: Adiciona workflows de Docker para HLG e produção
  .github/workflows/ci-hlg-docker.yaml
  .github/workflows/ci-hlg.yaml
  .github/workflows/ci-prod-docker.yaml
  .github/workflows/ci-prod.yaml
Labels: bug

#53 develop :green_heart: Atualiza fluxo de trabalho para uso do docker/build-push-action
  .github/workflows/ci-hlg-docker.yaml
Labels: bug

#54 develop :green_heart: Atualiza fluxo de trabalho para uso do docker/build-push-action
  .github/workflows/ci-hlg-docker.yaml
Labels: bug

#55 develop :green_heart: Atualiza fluxo de trabalho para uso do docker/build-push-action
  .github/workflows/ci-hlg-docker.yaml
  .github/workflows/ci-hlg.yaml
  .github/workflows/ci-prod-docker.yaml
  .github/workflows/ci-prod.yaml
  .github/workflows/sonar-cloud.yaml
Labels: bug

#59 feat/i35 :sparkles: [REST] - Implementação de Classe de Serviço para a Entity Donation
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/config/handler/ControllerExceptionHandler.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/dto/DonationDTO.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/enums/ExceptionDetails.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/DonationEntityFailuresException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/DonationEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DonationEntityServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DonationEntityServiceImplTest.java
Labels: feature

#61 feat/i33 :sparkles: [REST] - Implementação de Novo Endpoint para Registrar Doações para Abrigos
  README.md
  compose.yaml
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/ShelterController.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/ShelterControllerImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ReceiveDonationResponseFromShelterEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/request/ReceiveDonationRequest.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/response/ReceiveDonationResponse.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/DonationEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/ShelterEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DonationEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/core/utils/ValidationUtils.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ReceiveDonationResponseFromShelterEntityMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DonationEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImplTest.java
Labels: feature

#63 feat/i30 - [REST] - Criação de Novo Endpoint para Recuperação de Usuário
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/UserController.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/UserControllerImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/UserEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImplTest.java
Labels: feature

#65 feat/i60 :sparkles: [REST] - Alteração nas Mensagens de Erro da API para Torná-las Mais Amigáveis
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/config/handler/ControllerExceptionHandler.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/UserController.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/UserControllerImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/enums/ExceptionDetails.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/AddressEntityFailuresException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/ConstructorDefaultUndefinedException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/CustomException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/DetailsFailureException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/DonationEntityFailuresException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/MapperFailureException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/ShelterEntityFailuresException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/exception/UserEntityFailuresException.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/AddressEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/AddressMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/BuilderMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/DonationEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/DonationMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/MapperStrategy.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/repository/ShelterRepository.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/repository/UserRepository.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DonationEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/core/exception/ValidationUtilsException.java
  src/main/java/diegosneves/github/conectardoacoes/core/utils/ValidationUtils.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/AddressEntityMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/AddressMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/DonationEntityMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/DonationMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterEntityMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserEntityMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/UserMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/repository/ShelterRepositoryIntegrationTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/repository/UserRepositoryTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/AddressEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/DonationEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImplTest.java
Labels: Technical Debt

#64 feat/i32: [REST] - Criação de Novo Endpoint para Recuperar Abrigos por Usuário Responsável
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/ShelterController.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/controller/imp/ShelterControllerImpl.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/dto/DonationDTO.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ShelterInformationResponseFromShelterEntityMapper.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/response/ShelterInformationResponse.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/ShelterEntityService.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/mapper/ReceiveDonationResponseFromShelterEntityMapperTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImplTest.java
Labels: feature

#73 feat/i66 :recycle: [REST] - Adequação do UserEntityServiceImpl para uso do UserServiceContract
  Release_Notes.md
  pom.xml
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/repository/UserRepository.java
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImpl.java
  src/main/java/diegosneves/github/conectardoacoes/core/domain/user/shared/repository/UserContractRepository.java
  src/main/java/diegosneves/github/conectardoacoes/core/service/UserService.java
  src/main/java/diegosneves/github/conectardoacoes/core/service/UserServiceContract.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/repository/UserRepositoryTest.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/UserEntityServiceImplTest.java
  src/test/java/diegosneves/github/conectardoacoes/core/service/UserServiceTest.java
Labels: Technical Debt

#78 feat/i67 :art: [REST] - Adequação do ShelterEntityServiceImpl para uso do ShelterServiceContract
  src/main/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImpl.java
  src/test/java/diegosneves/github/conectardoacoes/adapters/rest/service/impl/ShelterEntityServiceImplTest.java
Labels: Technical Debt
